### ISSUE TITLE
Mac supports

### ISSUE THREAD

**Issue by podion** [parallaxinc/OpenSpin#10]
The file OpenSpin_x­x­x_x86_64­Mac.tar.bz2 dose not existe.

Thanks

**Comment by bweir** [comment]
You mean you want a Mac release build?

**Comment by cbmeeks** [comment]
How can we get a Mac release?  The IDE for Propeller really is awful and I'd like to use Sublime Text and then link/build/deploy using OpenSpin.

**Comment by bweir** [comment]
You can find Mac builds here:

https://github.com/bweir/OpenSpin/releases

Also, if there are features you'd like to see in PropellerIDE, I need more
information than it's "awful."

On Tue, Nov 24, 2015 at 5:07 PM, cbmeeks <notifications@github.com> wrote:

> How can we get a Mac release? The IDE for Propeller really is awful and
> I'd like to use Sublime Text and then link/build/deploy using OpenSpin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/parallaxinc/OpenSpin/issues/10#issuecomment-159453118>
> .
>



-- 
*Brett Weir*, Founder


Engineering Made Awesome
310.245.1775  • brett@lamestation.com • lamestation.com
