### ISSUE TITLE
OpenSpin accepts constant values larger than 32 bits

### ISSUE THREAD

**Issue by bweir** [parallaxinc/OpenSpin#23]
in PropTool, when constants exceed the maximum number of bits, the compiler complains.

![](http://forums.parallax.com/discussion/download/116224/pic07.PNG)

OpenSpin, it quietly accepts it even though the result is undefined. I played around with it and discovered that OpenSpin will apparently accept values of any size, no matter how large, like `$111111111100000000000000000000000000`.

**Comment by reltham** [comment]
Fix contained in Release 1.00.78

**Comment by bweir** [comment]
Thanks!

On Sat, Jan 16, 2016 at 4:09 PM, Roy Eltham <notifications@github.com>
wrote:

> Closed #23 <https://github.com/parallaxinc/OpenSpin/issues/23>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/parallaxinc/OpenSpin/issues/23#event-517115219>.
>



-- 
*Brett Weir*, Founder


Engineering Made Awesome
310.245.1775  • brett@lamestation.com • lamestation.com
