### ISSUE TITLE
Openspin bug

### ISSUE THREAD

**Issue by propellertools** [parallaxinc/OpenSpin#26]
I found a bug with openspin, it seems that the program size is calculated before unused code is removed using the -u command, I get object exceeds memory limits, my work around has been to use -M 35000 command so the program complies to 29K and runs fine

**Comment by PropGit** [comment]
@propellertools - thanks.  We are addressing this issue in the next release, which should be pretty soon.

**Comment by reltham** [comment]
Fixed in version 1.00.79
