### ISSUE TITLE
#warn vs #warning vs preprocessor's wiki page

### ISSUE THREAD

**Issue by drawkula** [parallaxinc/OpenSpin#33]
**Summary: `#warn` or `#warning`?**

```
(yeti@kumari:22)/opt/openspin/src/test$ cat PreProcessorTestWARN.spin 
#warn Testing WARN

pub main
        ' empty main to keep the compiler happy
(yeti@kumari:22)/opt/openspin/src/test$ /opt/openspin/bin/openspin -q PreProcessorTestWARN.spin 
PreProcessorTestWARN.spin(1:6) : error : Expected "," or end of line
Line:
#warn Testing WARN
Offending Item: Testing
(yeti@kumari:22)/opt/openspin/src/test$ cat PreProcessorTestWARNING.spin 
#warning Testing WARNING

pub main
        ' empty main to keep the compiler happy
(yeti@kumari:22)/opt/openspin/src/test$ /opt/openspin/bin/openspin -q PreProcessorTestWARNING.spin 
PreProcessorTestWARNING.spin:1: warning: #warn:  Testing WARNING
```
...so it seems to be `#warning`.

[The preprocessor's wiki page](https://github.com/parallaxinc/OpenSpin/wiki/Preprocessor) mentiones `#warn`.

And...
```
PreProcessorTestWARNING.spin:1: warning: #warn:  Testing WARNING
```
...probably would be...
```
PreProcessorTestWARNING.spin:1: warning: #warning:  Testing WARNING
```
...if [the text constant in the code](https://github.com/parallaxinc/OpenSpin/blob/master/PropellerCompiler/preprocess.cpp#L843) would reflect the choice of `#warning`.

**Comment by PropGit** [comment]
Thanks @drawkula.

@reltham - I'm voting for the  message to be: ```warning:  Testing WARNING``` i.e.: no repeating of the '#warning: ' directive at all, just the message provided by it (unless I'm misunderstanding the context here).

**Comment by PropGit** [comment]
Updated wiki to say #warning.

**Comment by drawkula** [comment]
\o/
I prefer `#warning` too...

If you strip `#warning` from the shown runtime output, I think `#error` should get the same treatment...
```
(yeti@kumari:13)/opt/openspin/src/test$ cat PreProcessorTestERROR.spin 
#error Testing ERROR

pub main
        ' empty main to keep the compiler happy
(yeti@kumari:13)/opt/openspin/src/test$ /opt/openspin/bin/openspin -q PreProcessorTestERROR.spin 
PreProcessorTestERROR.spin:1: error: #error:  Testing ERROR
```
Maybe keeping the `#` in both cases makes sense because someone might search the output for `#error` or `#warning`?

**Comment by PropGit** [comment]
Okay, I see your point, but it still seems so redundant.  It's always going to lead with ```error: #error:  ``` or ```warning: #warning:  ```

Anyone else want to share their thoughts on keeping/removing the directive (#error or #warning) from the output messages?

**Comment by drawkula** [comment]
@PropGit ... maybe repeating `error` and `warning` makes sense to distinguish them from not user generated errors and warnings.
```(yeti@kumari:13)/opt/openspin/src/test$ cat PreProcessorTestERROR-2.spin 
#include xyzzy
#error no string found for include

pub main
        ' empty main to keep the compiler happy
(yeti@kumari:13)/opt/openspin/src/test$ /opt/openspin/bin/openspin -q PreProcessorTestERROR-2.spin 
PreProcessorTestERROR-2.spin:1: error: no string found for include
PreProcessorTestERROR-2.spin:2: error: #error:  no string found for include
```

**Comment by drawkula** [comment]
`error`/`warning` for normal errors/warnings of parser and compiler and `#error`/`#warning` for the user chiseled ones?

**Comment by drawkula** [comment]
`bst_manual_0.04.pdf`, page 26: 

> bstc also supports #info / #warn / #error to allow comments to be inserted in the list file, or compilation to be halted with a user definable error message. Unlike the conditional statements, the #info / #warn / #error lines accept any message and will continue until the end of line.

Maybe BST(C)'s existence is a reason to allow `#warn` too and to add `#info`?

**Comment by PropGit** [comment]
> error/warning for normal errors/warnings of parser and compiler and #error/#warning for the user chiseled ones?

Okay, that's a good point.  We can leave the #error / #warning content as-is.

> Maybe BST(C)'s existence is a reason to allow #warn too and to add #info?

This wouldn't take too much to implement- I like it.  Closing this issue and creating two more for #warn and #info.
