### ISSUE TITLE
Allows #warn as an alias to #warning

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/OpenSpin#35]
This relates to Issue #33.

Add #warn as an alias to the #warning directive since there's an existing precedent in bstc for @warn.

Each should result in essentially the same output:

```#warn User-Message-Here```

generates

```warning: #warn:  User-Message-Here```

and 

```#warning User-Message-Here```

generates

```warning: #warning:  User-Message-Here```

**Comment by reltham** [comment]
This has been added.
