### ISSUE TITLE
Preprocessor clear defines

### ISSUE THREAD

**Issue by joerg-d** [parallaxinc/OpenSpin#6]
With the new function pp_clear_define_state in preprocess.c it is necessary to place the OBJ block before the first use (e.g. CON block with obj#constant). If I comment out pp_clear_define_state in preprocess.c, all sources are compiloe as before.

**Comment by PropGit** [comment]
We need an actual simple case (example code) that causes this problem, otherwise, we're not able to duplicate or address the issue.
